//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto01_ApiChamados.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chamado
    {
        public int ChamadoId { get; set; }
        public System.DateTime Data { get; set; }
        public string CpfCliente { get; set; }
        public string Assunto { get; set; }
        public string Descricao { get; set; }
        public string Resposta { get; set; }
    }
}
